version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    env_file: .env
    volumes:
      - ./prometheus/prometheus.yml.template:/etc/prometheus/prometheus.yml.template
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "9090:9090"
    entrypoint: ["/entrypoint.sh"]
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: always

networks:
  monitoring:

volumes:
  grafana-storage:
