version: '3.8'
services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile  # Asegúrate de que el Dockerfile se llame "Dockerfile" o ajusta el nombre aquí
    container_name: prometheus
    env_file: .env
    volumes:
      - ./prometheus/prometheus.yml.${ENVIRONMENT}:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ./.env:/etc/prometheus/.env # Copia el archivo .env al contenedor
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: always

networks:
  monitoring:

volumes:
  grafana-storage:
