global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus ejecutándose en 10.43.100.236

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - '10.43.101.180:9100'  # Node Exporter en Web Portal de Clientes
          - '10.43.101.107:9100'  # Node Exporter en Web Portal de Administradores
          - '10.43.101.212:9100'  # Node Exporter en API Gateway y otros servicios
          - '10.43.100.194:9100'  # Node Exporter en Servicio de Inventario
          - '10.43.100.236:9100'  # Node Exporter en Aplicación Autorización
          - '10.43.101.155:9100'  # Node Exporter en Cluster DB

  - job_name: 'web_portals'
    static_configs:
      - targets:
          - '10.43.101.180:9113'    # Nginx Web Client (Portal para Clientes)
          - '10.43.100.240:9113'    # Nginx Web Admin (Portal para Administradores)

  - job_name: 'load_balancer'
    static_configs:
      - targets:
          - '10.43.101.180:8100'  # Load Balancer en el puerto 8100

  - job_name: 'api_gateway_kong'
    static_configs:
      - targets:
          - '10.43.101.180:8000'  # Kong API Gateway en 10.43.101.180 (puerto HTTP)
          - '10.43.101.180:8001'  # Kong Admin API en 10.43.101.180 (puerto HTTP)
          - '10.43.101.212:8000'  # Kong API Gateway en 10.43.101.212 (puerto HTTP)
          - '10.43.101.212:8001'  # Kong Admin API en 10.43.101.212 (puerto HTTP)
          - '10.43.101.212:8443'  # Kong API Gateway en 10.43.101.212 (puerto HTTPS)
          - '10.43.101.212:8444'  # Kong Admin API en 10.43.101.212 (puerto HTTPS)

  - job_name: 'sv_users'
    static_configs:
      - targets:
          - '10.43.101.212:5293'  # Servicio de Usuarios (sv-users) en 10.43.101.212

  - job_name: 'sv_support'
    static_configs:
      - targets:
          - '10.43.101.212:8090'  # Servicio de Soporte (sv-support) en 10.43.101.212

  - job_name: 'sv_ecommerce'
    static_configs:
      - targets:
          - '10.43.100.194:8070'  # Servicio de E-Commerce en 10.43.100.194

  - job_name: 'sv_inventory'
    static_configs:
      - targets:
          - '10.43.100.194:8090'  # Servicio de Inventario en 10.43.100.194

  - job_name: 'authorization_app'
    static_configs:
      - targets:
          - '10.43.100.236:9600'  # Aplicación de Autorización en 10.43.100.236

  - job_name: 'database_postgresql'
    static_configs:
      - targets:
          - '10.43.101.107:5432'  # Base de datos PostgreSQL en 10.43.101.107
          - '10.43.101.108:5432'  # Base de datos PostgreSQL en 10.43.101.108

  - job_name: 'minio_service'
    static_configs:
      - targets:
          - '10.43.101.108:9000'  # MinIO en 10.43.101.108 (puerto 9000)
          - '10.43.101.108:9001'  # MinIO en 10.43.101.108 (puerto 9001)

  - job_name: 'sv_backadmin'
    static_configs:
      - targets:
          - '10.43.101.108:8090'  # Servicio BackAdmin (sv-backadmin) en 10.43.101.108
          
  - job_name: 'docker_status'
    static_configs:
      - targets:
          - '10.43.101.155:8081'  # Docker BackAdmin (sv-backadmin) en 10.43.101.155
          - '10.43.101.212:8081'  # Docker Support (sv-support) en 10.43.101.212
          - '10.43.100.194:8081'  # Docker ecommerce (sv-ecommerce) en 10.43.100.194
          - '10.43.101.180:8081'  # Docker front clientes (front cliente) en 10.43.101.180
          - '10.43.100.194:8082'  # Docker inventory (sv-inventory) en 10.43.100.194
          - '10.43.100.194:8082'  # Docker inventory (sv-inventory) en 10.43.100.194
          - '10.43.101.180:8084'  # Docker load balancer (load balancer) en 10.43.101.180
          - '10.43.101.155:8084'  # Docker load balancer (load balancer) en 10.43.101.180
          - '10.43.101.107:8081'  # Docker front admin (front admin)en 10.43.101.107
          - '10.43.101.107:8081'  # Docker front admin (front admin)en 10.43.101.107
          - '10.43.101.180:8085'  # Docker api 2 (apigetway)en 10.43.101.180
          - '10.43.101.212:8085'  # Docker api 2 (apigetway)en 10.43.101.212
          - '10.43.101.212:8082'  # Docker back users (sv-users)en 10.43.101.212
          - '10.43.101.155:8082'  # Docker minio (minio)en 10.43.101.212
          
