global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - '10.43.101.180:9100'  # Node Exporter en Web Portal de Clientes
          - '10.43.101.107:9100'  # Node Exporter en Web Portal de Administradores
          - '10.43.101.212:9100'  # Node Exporter en API Gateway y otros servicios
          - '10.43.100.194:9100'  # Node Exporter en Servicio de Inventario
          - '10.43.100.236:9100'  # Node Exporter en Aplicación Autorización
          - '10.43.101.155:9100'  # Node Exporter en Cluster DB

  - job_name: 'web_portals'
    static_configs:
      - targets:
          - '10.43.101.180:80'    # Web Portal para Clientes
          - '10.43.101.107:80'    # Web Portal para Administradores

  - job_name: 'api_gateway'
    static_configs:
      - targets:
          - '10.43.101.212:8000'  # API Gateway (Kong)

  - job_name: 'authentication_service'
    static_configs:
      - targets:
          - '10.43.101.180:9000'  # Servicio de autenticación en Web Portal de Clientes
          - '10.43.101.107:9000'  # Servicio de autenticación en Web Portal de Administradores

  - job_name: 'service_support'
    static_configs:
      - targets:
          - '10.43.101.212:9200'  # Servicio de Soporte

  - job_name: 'service_users'
    static_configs:
      - targets:
          - '10.43.101.212:9300'  # Servicio de Usuarios

  - job_name: 'service_inventory'
    static_configs:
      - targets:
          - '10.43.100.194:9400'  # Servicio de Inventario

  - job_name: 'service_orders'
    static_configs:
      - targets:
          - '10.43.100.194:9500'  # Servicio de Órdenes

  - job_name: 'authorization_app'
    static_configs:
      - targets:
          - '10.43.100.236:9600'  # Aplicación de Autorización

  - job_name: 'database_cluster'
    static_configs:
      - targets:
          - '10.43.101.155:5432'  # Base de datos (puerto estándar PostgreSQL)
